[workspace]
members = [
    "analytics",
    "cli",
    "config",
    "db",
    "liquidator",
    "rpc_utils",
    "scrapers"
]
[profile.release]
opt-level = 3
incremental = false
codegen-units = 1 
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1 