version: "3.0"
services:
  postgres:
    image: postgres:13.4
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "liquidator"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"